spring:
  application:
    name: question-bank
server:
  port: 8080
logging:
  file:
    path: /static
    name: mylogger
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method
    #custom path for api docs
    url: /doc/openapi.json